services:
  postgres-btj:
    image: ghcr.io/baosystems/postgis:16-3.5
    container_name: data-wrangling-btj
    environment:
      POSTGRES_USER: btj_academy
      POSTGRES_PASSWORD: btj_academy
      POSTGRES_DB: btj_academy
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data:/var/csv
      - ./sql:/docker-entrypoint-initdb.d